# Generated by Django 3.0.6 on 2021-01-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200618_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='rooms_thumbnail'),
        ),
    ]
